#!/usr/bin/env python3
"""Verify the initial subset-sum interval certificate for the fixed case D={3,4,7}, k=1."""

initial = [3, 4, 7, 9, 16, 27, 49, 64, 81, 243, 256, 343, 729, 1024, 2187]

sums = {0}
for x in initial:
    sums |= {s + x for s in list(sums)}

missing = [n for n in range(582, 4461) if n not in sums]

print("INITIAL INTERVAL CERTIFICATE")
print("terms =", initial)
print("interval = [582,4460]")
print("total subset sums generated =", len(sums))

if missing:
    print("STATUS: FAIL")
    print("missing count =", len(missing))
    print("first missing values =", missing[:20])
    raise SystemExit(1)

print("STATUS: PASS")
print("[582,4460] is contained in the subset-sum set generated by the listed terms.")
